kind: pipeline
name: pygna

steps:
- name: install-py3.5
  image: python:3.5
  commands:
  - pip install .
  - pygna

- name: build
  image: python:3.5
  commands:
  - python setup.py sdist bdist_wheel

# - name: publish
#   image: python:3.5
#   environment:
#     TWINE_USERNAME:
#       from_secret: TWINE_USERNAME
#     TWINE_PASSWORD:
#       from_secret: TWINE_PASSWORD
#   commands:
#   - pip install twine
#   - twine upload --repository-url https://test.pypi.org/legacy/ dist/*

- name: conda
  image: continuumio/miniconda3
  environment:
    ANACONDA_API_TOKEN:
        from_secret: ANACONDA_TOKEN
  commands:
  - conda config --set always_yes yes
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda install conda-build anaconda-client
  - conda config --set anaconda_upload yes
  - conda build .
