kind: pipeline
name: pygna

steps:
- name: install-py3.5
  image: python:3.5
  commands:
  - pip install .
  - pygna

- name: build
  image: python:3.5
  commands:
  - python setup.py sdist bdist_wheel

- name: publish
  image: python:3.5
  commands:
  - twine upload --repository testpy dist/*
