name: pygnas
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - pandas
  - snakemake
  - bumpversion 
  - sphinx
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - pytables>=3.4.4
  - seaborn>=0.9
  - palettable
  - networkx>=2.2
  - argh
