name: pygna
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.5
  - argh
  - snakemake
  - pandas
  - bumpversion
  - sphinx
  - networkx>=2.2
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - pytables>=3.4.4
  - seaborn>=0.9
  - palettable
