name: pygna
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.5
  - argh
  - snakemake
  - pandas
  - bumpversion
  - sphinx
  - numpy
  - scipy
  - matplotlib
  - pyyaml
