name: pygna
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7.2
  - pandas
  - bumpversion
  - snakemake
  - sphinx
  - sphinx_rtd_theme
  - networkx>=2.2
  - numpy
  - scipy
  - matplotlib
  - argh
  - pytables>=3.4.4
  - seaborn>=0.9
  - palettable