version: 2.1

jobs:
  build_conda_package:

    parameters:
        python-version:
            type: string
            default: "3.7"
        numpy-version:
            type: string
            default: "1.15"
        build-label:
            type: string
            default: "main"

    docker:
      - image: continuumio/miniconda3

    steps:
        - checkout
        - restore_cache:
            keys:
                - miniconda-pkg-py3.7-{{ .Branch }}-{{ checksum ".conda_recipe/meta.yaml" }}
        - run:
            name: Configure Miniconda
            command: |
                conda config --set always_yes yes
                conda update -q conda
                conda config --add channels bioconda
                conda config --add channels conda-forge
                conda install conda-build
                conda install -c anaconda anaconda-client
        - run:
            name: Build package
            command: |
                conda build .conda_recipe -c bioconda -c conda-forge \
                --python 3.7 \
                --numpy 1.15
        - save_cache:
            paths:
                - /opt/conda/pkgs
            key: miniconda-pkg-py3.7-{{ .Branch }}-{{ checksum ".conda_recipe/meta.yaml" }}

        - run:
            name: Convert package
            command: |
                export TMP_PACKAGE_BUILD=`conda build .conda_recipe --output -c bioconda \
                -c conda-forge --python 3.7 \
                 --numpy 1.15 | grep bz2`
                mkdir ${HOME}/conda-bld/
                conda convert --platform osx-64 ${TMP_PACKAGE_BUILD} -o ${HOME}/conda-bld/
                conda convert --platform linux-32 ${TMP_PACKAGE_BUILD} -o ${HOME}/conda-bld/
                conda convert --platform linux-64 ${TMP_PACKAGE_BUILD} -o ${HOME}/conda-bld/
        - run:
            name: Upload package
            command: |
                export TMP_PACKAGE_BUILD=`conda build .conda_recipe --output -c bioconda \
                -c conda-forge --python << parameters.python-version >> \
                 --numpy 1.15 | grep bz2`
                anaconda -t ${UPLOAD_TOKEN} upload --force -u stracquadaniolab \
                -l 3.1.0 ${TMP_PACKAGE_BUILD}
                anaconda -t ${UPLOAD_TOKEN} upload --force -u stracquadaniolab \
                -l 3.1.0 ${HOME}/conda-bld/**/*.bz2


workflows:
    commit_to_conda:
        jobs:
            - build_conda_package:
                python-version: "3.7"
                numpy-version: "1.15"
                context: ANACONDA_CLOUD_DEPLOY
