package:
  name: pygna
  version: 2.2.4

source:
  path: ..

build:
  entry_points:
      - pygna = cli:main

requirements:
  build:
    - adjustText
    - pandas
    - numpy>=1.16.3
    - scipy
    - matplotlib
    - pyyaml
    - tables>=3.4.4
    - seaborn>=0.9
    - palettable
    - networkx<=2.3
    - statsmodels
    - argh

  run:
    - adjustText
    - pandas
    - numpy>=1.16.3
    - scipy
    - matplotlib
    - pyyaml
    - tables>=3.4.4
    - seaborn>=0.9
    - palettable
    - networkx<=2.3
    - statsmodels
    - argh

test:
  commands:
    - pygna -h

about:
  home: https://github.com/stracquadaniolab/pygna
  summary: PyGNA, a unified framework for geneset network analysis
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/stracquadaniolab/pygna
  doc_url: https://pygna.readthedocs.io/
  description: |
    PyGNA is a unified framework for network analysis of high-throughput
    experiment results. It can be used both as a standalone command line
    application or it can be included as a package in your own python code.
