name: "Build"

on:
    push:
        branches:
        - '*'

jobs:
  release:
    name: "Build, compile and upload"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: pygna
    strategy:
      matrix:
        python: [3.8]
        numpy: [1.15]
    steps:
      - uses: actions/checkout@v1
      - name: "Setup Conda"
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python }}
          conda-channels: anaconda, conda-forge, bioconda

      - name: "Install Conda development packages"
        run: |
            conda install conda-build
            conda install -c anaconda anaconda-client

      - name: "Build Conda package"
        run: |
            mkdir conda-build
            conda build . --no-build-id --numpy ${{ matrix.numpy }} --output-folder ./conda-build
            conda convert -p all ./conda-build/**/pygna*.bz2 --output-dir ./conda-build

      - name: "Setup Python for PIP"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "Install PIP required packages"
        run: pip install wheel twine

      - name: "Build PIP package"
        run: python setup.py sdist bdist_wheel
