name: "Release"

on:
    push:
        tags:
        - '*'

jobs:
  release:
    name: "Build and release"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: pygna
    strategy:
      matrix:
        python: [3.8]
        numpy: [1.15]
    steps:
      - uses: actions/checkout@v1

      - name: "Setup Python"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: "Install PIP required packages"
        run: pip install wheel twine

      - name: "Build PIP package"
        run: python setup.py sdist bdist_wheel

      - name: "Publish package on PyPi"
        run: twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{secrets.PYPI_PASSWORD}} dist/*

      - name: "Setup Conda"
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python }}
          conda-channels: anaconda, conda-forge, bioconda

      - name: "Install Conda development packages"
        run: |
            conda install conda-build
            conda install -c anaconda anaconda-client

      - name: "Build Conda package"
        run: |
            mkdir conda-build
            conda build . --no-build-id --numpy ${{ matrix.numpy }} --output-folder ./conda-build
            conda convert -p all ./conda-build/**/pygna*.bz2 --output-dir ./conda-build

      - name: "Upload Conda package"
        run: anaconda -t ${{ secrets.ANACONDA_API_TOKEN }} upload --force -u stracquadaniolab --no-progress ./conda-build/**/pygna*.bz2

      - name: "Build the Docker image"
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/dockerfile
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/pygna
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
          username: ${{ github.ref }}
          password: ${{ secrets.GH_TOKEN }}
